# Generated by Django 3.2.24 on 2024-06-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoals',
            name='children',
        ),
        migrations.RemoveField(
            model_name='usergoals',
            name='parent',
        ),
    ]
