# Generated by Django 5.0.6 on 2024-05-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_usergoals_deadline_near_low_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergoals',
            old_name='achieve_by',
            new_name='deadline',
        ),
    ]
