# Generated by Django 5.0.6 on 2024-05-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_achieve_by_usergoals_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergoals',
            old_name='deadline',
            new_name='achieve_by',
        ),
    ]
