# Generated by Django 5.0.6 on 2024-05-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_rename_deadline_usergoals_achieve_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoals',
            name='deadline_near_low',
        ),
        migrations.RemoveField(
            model_name='usergoals',
            name='deadline_near_mid',
        ),
    ]
