# Generated by Django 3.2.24 on 2024-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refine',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_pdrfdn', upload_to='images/'),
        ),
    ]
