# Generated by Django 5.0.6 on 2024-05-21 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='refine',
            old_name='rank',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='refine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refine', to=settings.AUTH_USER_MODEL),
        ),
    ]
