# Generated by Django 5.0.6 on 2024-05-27 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0005_remove_usergoals_deadline_near_low_and_more'),
        ('refine', '0002_rename_rank_refine_priority_alter_refine_owner'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('today', models.BooleanField(default=False)),
                ('achieved', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('achieve_by', models.DateTimeField(blank=True, null=True)),
                ('currently_active', models.BooleanField(default=True)),
                ('Refine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_for_refine', to='refine.refine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tags')),
                ('usergoals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_for_usergoals', to='goals.usergoals')),
            ],
        ),
    ]
