# Generated by Django 3.2.24 on 2024-06-26 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('refine', '0001_initial'),
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('today', models.BooleanField(default=False)),
                ('achieved', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('achieve_by', models.DateTimeField(blank=True, null=True)),
                ('currently_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('refine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_for_refine', to='refine.refine')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tags')),
                ('usergoals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_for_usergoals', to='goals.usergoals')),
            ],
        ),
    ]
