# Generated by Django 5.0.6 on 2024-05-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Refine',
            new_name='refine',
        ),
    ]
